var replacements = {
	"corso Liberta` 1": "corso Libertà 1",
	"corso Liberta` 2": "corso Libertà 2",
	"corso Liberta` 3": "corso Libertà 3",
	"corso Liberta` 4": "corso Libertà 4",
	"pizza S.Urbano": "piazza S.Urbano",
	"Z. Artigianale": "Zona Artigianale",
	"Ponte Adige Staz.": "Ponte Adige Stazione",
	"Ponte Adige Staz. 2": "Ponte Adige Stazione 2",
	"via S. Giacomo 6": "via San Giacomo 6",
	"via Braille/Bz Sud": "via Braille (BZ Sud)",
	"piazza Universit": "piazza Università",
	"S.Maurizio Moosbauer": "San Maurizio Moosbauer",
	"S.Maurizio Pircher": "San Maurizio Pircher",
	"via Duca d`Aosta": "via Duca d'Aosta",
	"via S. Antonio": "via San Antonio",
	"via S. Geltrude 1": "via San Geltrude 1",
	"via S. Geltrude 2": "via San Geltrude 2",
	"via S. Giacomo 1": "via San Giacomo 1",
	"via S. Maurizio 1": "via San Maurizio 1",
	"via S. Maurizio 2": "via San Maurizio 2",
	"via S. Vigilio 1": "via San Vigilio 1",
	"via S. Vigilio 2": "via San Vigilio 2",
	"Berghuetten": "Berghütten",
	"Sant`Anna": "Sant'Anna",
	"Z.Industriale1": "zona Industriale 1",
	"Z.Industriale 2": "zona Industriale 2",
	"Z.Industriale 3": "zona Industriale 3",
	"Fonte S. Martino": "Fonte San Martino",
	"Fun. Merano 2000": "Funivia Merano 2000",
	"Maia Bassa Staz.": "Maia Bassa Stazione",
	"Sinigo Zona Artig.": "Sinigo Zona Artigianale",
	"via S. Francesco": "via San Francesco",
	"via S. Valentino": "via San Valentino",
	"via S. Valentino 1": "via San Valentino 1",
	"via Andriano/Huben": "via Andriano (Huben)",
	"Fun. Verano": "Funivia Verano",
	"Settequerce z.art.": "Settequerce Zona Artigianale",
	"vic. al Monte": "vicolo al Monte",
	"Parkpl. Nusser": "Parkplatz Nusser",
	"Mazzini Pl.": "Mazziniplatz",
	"Verdi Pl.": "Verdiplatz",
	"Siegespl. 1": "Siegesplatz 1",
	"Siegespl. 2": "Siegesplatz 2",
	"Walther Pl.": "Waltherplatz",
	"Kampill Br.": "Kampillbrücke",
	"Drusus Br.": "Drususbrücke",
	"S. Moritzing Pircher": "St. Moritzing Pircher",
	"Stadium Europa": "Europastadium",
	"Braille Str./Bz S": "Braille Str. (BZ Süd)",
	"Duca d`Aosta Str.": "Duca d'Aosta Str.",
	"Branzoll SS12Raif": "Branzoll SS12 Raif",
	"Kardaun Handwerkerz.": "Kardaun Handwerkerzone",
	"IZ.": "Industriezone",
	"Laendgasse": "Ländgasse",
	"Marlinger Br.": "Marlinger Brücke",
	"Seilb. Meran 2000": "Seilbahn Meran 2000",
	"Brunnenpl.": "Brunnenplatz",
	"Theater Pl.": "Theaterplatz",
	"Rametz Br.": "Rametzbrücke",
	"Sinich HW Zone": "Sinich Handwerkerzone",
	"Brunnen Platz": "Brunnenplatz",
	"Andrianerstr./Huben": "Andrianerstr. (Huben)",
	"Toell Bahnhof": "Töll Bahnhof",
	"Toell 1": "Töll 1",
	"Toell 2": "Töll 2",
	"Toell 3": "Töll 3",
	"Seilb. Voeran": "Seilbahn Voeran",
	"Seilb. Moelten": "Seilbahn Moelten",
};